# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import BuildTest_pb2 as BuildTest__pb2


class BuildTestServicesStub(object):
    """Services associated
    Generates pseudo package from information transmitted from client,  returns a status message depending upon result
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Build = channel.unary_unary(
                '/BuildTest.BuildTestServices/Build',
                request_serializer=BuildTest__pb2.PackageInfo.SerializeToString,
                response_deserializer=BuildTest__pb2.BuildInfo.FromString,
                )
        self.Test = channel.unary_unary(
                '/BuildTest.BuildTestServices/Test',
                request_serializer=BuildTest__pb2.PackageInfo.SerializeToString,
                response_deserializer=BuildTest__pb2.BuildInfo.FromString,
                )


class BuildTestServicesServicer(object):
    """Services associated
    Generates pseudo package from information transmitted from client,  returns a status message depending upon result
    """

    def Build(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildTestServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Build': grpc.unary_unary_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=BuildTest__pb2.PackageInfo.FromString,
                    response_serializer=BuildTest__pb2.BuildInfo.SerializeToString,
            ),
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=BuildTest__pb2.PackageInfo.FromString,
                    response_serializer=BuildTest__pb2.BuildInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BuildTest.BuildTestServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuildTestServices(object):
    """Services associated
    Generates pseudo package from information transmitted from client,  returns a status message depending upon result
    """

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuildTest.BuildTestServices/Build',
            BuildTest__pb2.PackageInfo.SerializeToString,
            BuildTest__pb2.BuildInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuildTest.BuildTestServices/Test',
            BuildTest__pb2.PackageInfo.SerializeToString,
            BuildTest__pb2.BuildInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
