# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import FileTransfer_pb2 as FileTransfer__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Download = channel.unary_stream(
                '/FileTransfer.FileService/Download',
                request_serializer=FileTransfer__pb2.Request.SerializeToString,
                response_deserializer=FileTransfer__pb2.File.FromString,
                )
        self.Upload = channel.stream_unary(
                '/FileTransfer.FileService/Upload',
                request_serializer=FileTransfer__pb2.File.SerializeToString,
                response_deserializer=FileTransfer__pb2.Response.FromString,
                )
        self.NameFile = channel.unary_unary(
                '/FileTransfer.FileService/NameFile',
                request_serializer=FileTransfer__pb2.Request.SerializeToString,
                response_deserializer=FileTransfer__pb2.Response.FromString,
                )


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NameFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=FileTransfer__pb2.Request.FromString,
                    response_serializer=FileTransfer__pb2.File.SerializeToString,
            ),
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=FileTransfer__pb2.File.FromString,
                    response_serializer=FileTransfer__pb2.Response.SerializeToString,
            ),
            'NameFile': grpc.unary_unary_rpc_method_handler(
                    servicer.NameFile,
                    request_deserializer=FileTransfer__pb2.Request.FromString,
                    response_serializer=FileTransfer__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FileTransfer.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FileTransfer.FileService/Download',
            FileTransfer__pb2.Request.SerializeToString,
            FileTransfer__pb2.File.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/FileTransfer.FileService/Upload',
            FileTransfer__pb2.File.SerializeToString,
            FileTransfer__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NameFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FileTransfer.FileService/NameFile',
            FileTransfer__pb2.Request.SerializeToString,
            FileTransfer__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
