# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.network_interface.ServerUtils.ServerUtils_pb2 as ServerUtils__pb2


class ServerUtilsServicesStub(object):
    """Services associated with utility operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ServerUtils.ServerUtilsServices/Ping',
                request_serializer=ServerUtils__pb2.ClientInfo.SerializeToString,
                response_deserializer=ServerUtils__pb2.ServerInfo.FromString,
                )


class ServerUtilsServicesServicer(object):
    """Services associated with utility operations
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerUtilsServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ServerUtils__pb2.ClientInfo.FromString,
                    response_serializer=ServerUtils__pb2.ServerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServerUtils.ServerUtilsServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerUtilsServices(object):
    """Services associated with utility operations
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerUtils.ServerUtilsServices/Ping',
            ServerUtils__pb2.ClientInfo.SerializeToString,
            ServerUtils__pb2.ServerInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
