# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerUtils.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServerUtils.proto',
  package='ServerUtils',
  syntax='proto3',
  serialized_options=b'Z\r./ServerUtils',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11ServerUtils.proto\x12\x0bServerUtils\"\x1a\n\nClientInfo\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\"\x1a\n\nServerInfo\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2O\n\x13ServerUtilsServices\x12\x38\n\x04Ping\x12\x17.ServerUtils.ClientInfo\x1a\x17.ServerUtils.ServerInfoB\x0fZ\r./ServerUtilsb\x06proto3'
)




_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='ServerUtils.ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='ServerUtils.ClientInfo.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=60,
)


_SERVERINFO = _descriptor.Descriptor(
  name='ServerInfo',
  full_name='ServerUtils.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='ServerUtils.ServerInfo.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['ServerInfo'] = _SERVERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'ServerUtils_pb2'
  # @@protoc_insertion_point(class_scope:ServerUtils.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

ServerInfo = _reflection.GeneratedProtocolMessageType('ServerInfo', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO,
  '__module__' : 'ServerUtils_pb2'
  # @@protoc_insertion_point(class_scope:ServerUtils.ServerInfo)
  })
_sym_db.RegisterMessage(ServerInfo)


DESCRIPTOR._options = None

_SERVERUTILSSERVICES = _descriptor.ServiceDescriptor(
  name='ServerUtilsServices',
  full_name='ServerUtils.ServerUtilsServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=169,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='ServerUtils.ServerUtilsServices.Ping',
    index=0,
    containing_service=None,
    input_type=_CLIENTINFO,
    output_type=_SERVERINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERUTILSSERVICES)

DESCRIPTOR.services_by_name['ServerUtilsServices'] = _SERVERUTILSSERVICES

# @@protoc_insertion_point(module_scope)
