# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MemberOperations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MemberOperations.proto',
  package='MemberOperations',
  syntax='proto3',
  serialized_options=b'Z\023./member-operations',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16MemberOperations.proto\x12\x10MemberOperations\">\n\rMemberRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\":\n\x0eMemberResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x16\n\x0ewas_successful\x18\x02 \x01(\x08\"^\n\x1bMemberAuthenticationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x10\n\x08is_level\x18\x04 \x01(\x08\"J\n\x1cMemberAuthenticationResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x18\n\x10is_authenticated\x18\x02 \x01(\x08\x32\xba\x01\n\x12MemberCRUDServices\x12Q\n\x0c\x43reateMember\x12\x1f.MemberOperations.MemberRequest\x1a .MemberOperations.MemberResponse\x12Q\n\x0cRemoveMember\x12\x1f.MemberOperations.MemberRequest\x1a .MemberOperations.MemberResponse2\x8b\x01\n\x14MemberAuthentication\x12s\n\x12\x41uthenticateMember\x12-.MemberOperations.MemberAuthenticationRequest\x1a..MemberOperations.MemberAuthenticationResponseB\x15Z\x13./member-operationsb\x06proto3'
)




_MEMBERREQUEST = _descriptor.Descriptor(
  name='MemberRequest',
  full_name='MemberOperations.MemberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MemberOperations.MemberRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='MemberOperations.MemberRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='MemberOperations.MemberRequest.level', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=106,
)


_MEMBERRESPONSE = _descriptor.Descriptor(
  name='MemberResponse',
  full_name='MemberOperations.MemberResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='MemberOperations.MemberResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='was_successful', full_name='MemberOperations.MemberResponse.was_successful', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=166,
)


_MEMBERAUTHENTICATIONREQUEST = _descriptor.Descriptor(
  name='MemberAuthenticationRequest',
  full_name='MemberOperations.MemberAuthenticationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MemberOperations.MemberAuthenticationRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='MemberOperations.MemberAuthenticationRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='MemberOperations.MemberAuthenticationRequest.level', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_level', full_name='MemberOperations.MemberAuthenticationRequest.is_level', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=262,
)


_MEMBERAUTHENTICATIONRESPONSE = _descriptor.Descriptor(
  name='MemberAuthenticationResponse',
  full_name='MemberOperations.MemberAuthenticationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='MemberOperations.MemberAuthenticationResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_authenticated', full_name='MemberOperations.MemberAuthenticationResponse.is_authenticated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=338,
)

DESCRIPTOR.message_types_by_name['MemberRequest'] = _MEMBERREQUEST
DESCRIPTOR.message_types_by_name['MemberResponse'] = _MEMBERRESPONSE
DESCRIPTOR.message_types_by_name['MemberAuthenticationRequest'] = _MEMBERAUTHENTICATIONREQUEST
DESCRIPTOR.message_types_by_name['MemberAuthenticationResponse'] = _MEMBERAUTHENTICATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemberRequest = _reflection.GeneratedProtocolMessageType('MemberRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERREQUEST,
  '__module__' : 'MemberOperations_pb2'
  # @@protoc_insertion_point(class_scope:MemberOperations.MemberRequest)
  })
_sym_db.RegisterMessage(MemberRequest)

MemberResponse = _reflection.GeneratedProtocolMessageType('MemberResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERRESPONSE,
  '__module__' : 'MemberOperations_pb2'
  # @@protoc_insertion_point(class_scope:MemberOperations.MemberResponse)
  })
_sym_db.RegisterMessage(MemberResponse)

MemberAuthenticationRequest = _reflection.GeneratedProtocolMessageType('MemberAuthenticationRequest', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERAUTHENTICATIONREQUEST,
  '__module__' : 'MemberOperations_pb2'
  # @@protoc_insertion_point(class_scope:MemberOperations.MemberAuthenticationRequest)
  })
_sym_db.RegisterMessage(MemberAuthenticationRequest)

MemberAuthenticationResponse = _reflection.GeneratedProtocolMessageType('MemberAuthenticationResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEMBERAUTHENTICATIONRESPONSE,
  '__module__' : 'MemberOperations_pb2'
  # @@protoc_insertion_point(class_scope:MemberOperations.MemberAuthenticationResponse)
  })
_sym_db.RegisterMessage(MemberAuthenticationResponse)


DESCRIPTOR._options = None

_MEMBERCRUDSERVICES = _descriptor.ServiceDescriptor(
  name='MemberCRUDServices',
  full_name='MemberOperations.MemberCRUDServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=341,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateMember',
    full_name='MemberOperations.MemberCRUDServices.CreateMember',
    index=0,
    containing_service=None,
    input_type=_MEMBERREQUEST,
    output_type=_MEMBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveMember',
    full_name='MemberOperations.MemberCRUDServices.RemoveMember',
    index=1,
    containing_service=None,
    input_type=_MEMBERREQUEST,
    output_type=_MEMBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEMBERCRUDSERVICES)

DESCRIPTOR.services_by_name['MemberCRUDServices'] = _MEMBERCRUDSERVICES


_MEMBERAUTHENTICATION = _descriptor.ServiceDescriptor(
  name='MemberAuthentication',
  full_name='MemberOperations.MemberAuthentication',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=530,
  serialized_end=669,
  methods=[
  _descriptor.MethodDescriptor(
    name='AuthenticateMember',
    full_name='MemberOperations.MemberAuthentication.AuthenticateMember',
    index=0,
    containing_service=None,
    input_type=_MEMBERAUTHENTICATIONREQUEST,
    output_type=_MEMBERAUTHENTICATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEMBERAUTHENTICATION)

DESCRIPTOR.services_by_name['MemberAuthentication'] = _MEMBERAUTHENTICATION

# @@protoc_insertion_point(module_scope)
