# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.network_interface.member_operations.MemberOperations_pb2 as MemberOperations__pb2


class MemberCRUDServicesStub(object):
    """CRUD operations associated with members
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMember = channel.unary_unary(
                '/MemberOperations.MemberCRUDServices/CreateMember',
                request_serializer=MemberOperations__pb2.MemberRequest.SerializeToString,
                response_deserializer=MemberOperations__pb2.MemberResponse.FromString,
                )
        self.RemoveMember = channel.unary_unary(
                '/MemberOperations.MemberCRUDServices/RemoveMember',
                request_serializer=MemberOperations__pb2.MemberRequest.SerializeToString,
                response_deserializer=MemberOperations__pb2.MemberResponse.FromString,
                )


class MemberCRUDServicesServicer(object):
    """CRUD operations associated with members
    """

    def CreateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberCRUDServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=MemberOperations__pb2.MemberRequest.FromString,
                    response_serializer=MemberOperations__pb2.MemberResponse.SerializeToString,
            ),
            'RemoveMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMember,
                    request_deserializer=MemberOperations__pb2.MemberRequest.FromString,
                    response_serializer=MemberOperations__pb2.MemberResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MemberOperations.MemberCRUDServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MemberCRUDServices(object):
    """CRUD operations associated with members
    """

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MemberOperations.MemberCRUDServices/CreateMember',
            MemberOperations__pb2.MemberRequest.SerializeToString,
            MemberOperations__pb2.MemberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MemberOperations.MemberCRUDServices/RemoveMember',
            MemberOperations__pb2.MemberRequest.SerializeToString,
            MemberOperations__pb2.MemberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MemberAuthenticationStub(object):
    """Authentication operations associated with members
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthenticateMember = channel.unary_unary(
                '/MemberOperations.MemberAuthentication/AuthenticateMember',
                request_serializer=MemberOperations__pb2.MemberAuthenticationRequest.SerializeToString,
                response_deserializer=MemberOperations__pb2.MemberAuthenticationResponse.FromString,
                )


class MemberAuthenticationServicer(object):
    """Authentication operations associated with members
    """

    def AuthenticateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemberAuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthenticateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateMember,
                    request_deserializer=MemberOperations__pb2.MemberAuthenticationRequest.FromString,
                    response_serializer=MemberOperations__pb2.MemberAuthenticationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MemberOperations.MemberAuthentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MemberAuthentication(object):
    """Authentication operations associated with members
    """

    @staticmethod
    def AuthenticateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MemberOperations.MemberAuthentication/AuthenticateMember',
            MemberOperations__pb2.MemberAuthenticationRequest.SerializeToString,
            MemberOperations__pb2.MemberAuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
