# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProjectOperations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ProjectOperations.proto\x12\x11ProjectOperations\"\x1e\n\x0eProjectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0fProjectResponse\x12\r\n\x05\x65xist\x18\x01 \x01(\x08\x32o\n\x18ProjectOperationServices\x12S\n\nGetProject\x12!.ProjectOperations.ProjectRequest\x1a\".ProjectOperations.ProjectResponseB\x15Z\x13./ProjectOperationsb\x06proto3')



_PROJECTREQUEST = DESCRIPTOR.message_types_by_name['ProjectRequest']
_PROJECTRESPONSE = DESCRIPTOR.message_types_by_name['ProjectResponse']
ProjectRequest = _reflection.GeneratedProtocolMessageType('ProjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTREQUEST,
  '__module__' : 'ProjectOperations_pb2'
  # @@protoc_insertion_point(class_scope:ProjectOperations.ProjectRequest)
  })
_sym_db.RegisterMessage(ProjectRequest)

ProjectResponse = _reflection.GeneratedProtocolMessageType('ProjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTRESPONSE,
  '__module__' : 'ProjectOperations_pb2'
  # @@protoc_insertion_point(class_scope:ProjectOperations.ProjectResponse)
  })
_sym_db.RegisterMessage(ProjectResponse)

_PROJECTOPERATIONSERVICES = DESCRIPTOR.services_by_name['ProjectOperationServices']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023./ProjectOperations'
  _PROJECTREQUEST._serialized_start=46
  _PROJECTREQUEST._serialized_end=76
  _PROJECTRESPONSE._serialized_start=78
  _PROJECTRESPONSE._serialized_end=110
  _PROJECTOPERATIONSERVICES._serialized_start=112
  _PROJECTOPERATIONSERVICES._serialized_end=223
# @@protoc_insertion_point(module_scope)
