# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.network_interface.ProjectOperations.ProjectOperations_pb2 as ProjectOperations__pb2


class ProjectOperationServicesStub(object):
    """Services associated with package operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProject = channel.unary_unary(
                '/ProjectOperations.ProjectOperationServices/GetProject',
                request_serializer=ProjectOperations__pb2.ProjectRequest.SerializeToString,
                response_deserializer=ProjectOperations__pb2.ProjectResponse.FromString,
                )


class ProjectOperationServicesServicer(object):
    """Services associated with package operations
    """

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectOperationServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=ProjectOperations__pb2.ProjectRequest.FromString,
                    response_serializer=ProjectOperations__pb2.ProjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProjectOperations.ProjectOperationServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProjectOperationServices(object):
    """Services associated with package operations
    """

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProjectOperations.ProjectOperationServices/GetProject',
            ProjectOperations__pb2.ProjectRequest.SerializeToString,
            ProjectOperations__pb2.ProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
